#!/usr/bin/env python3

# A Boto3 enabled wrapper script for monitoring and managing ec2 instances
# 
# Author: Prashant Pokhriyal
#

import sys
from ec2.main import main

if __name__ == "__main__":
    sys.exit(main())